services:
    app:
        build: .
        container_name: hotel_app
        image: tmquang0209/hotel-booking:latest
        ports:
            - "3000:3000"
        depends_on:
            - redis
        volumes:
            - .:/app
        working_dir: /app
        command: yarn start
        environment:
            - PORT=3000
            - MYSQL_HOST=103.200.22.212
            - MYSQL_PORT=3306
            - MYSQL_USERNAME=tmquangt_hotel
            - MYSQL_DATABASE=tmquangt_hotel
            - MYSQL_PASSWORD=Matkhau123@@
            - JWT_SECRET=PyCJtD935qHpaOFK6KM0DxzYTipVkNMG
            - JWT_REFRESH=oaAq0remB5b7dCDNGyyqQjT5vSd9fzzq
            - REDIS_HOST=hotel_redis
        networks:
            - hotel_booking_hotel-net # Đảm bảo tên mạng chính xác

    redis:
        image: redis:6.0.16-alpine
        container_name: hotel_redis
        command: redis-server --appendonly yes --bind 0.0.0.0
        ports:
            - "6379:6379"
        networks:
            - hotel_booking_hotel-net # Đảm bảo tên mạng chính xác
        volumes:
            - redis_data:/data

    redis-cli:
        image: redis:6.0.16-alpine
        container_name: redis_cli
        depends_on:
            - redis
        command: redis-cli -h redis
        stdin_open: true
        tty: true
        networks:
            - hotel_booking_hotel-net # Đảm bảo tên mạng chính xác

volumes:
    redis_data:

networks:
    hotel_booking_hotel-net:
        driver: bridge
