services:
    app:
        build: .
        container_name: hotel_app
        image: tmquang0209/hotel-booking:latest
        ports:
            - "3000:3000"
        depends_on:
            - redis
        volumes:
            - .:/app
        working_dir: /app
        command: yarn start
        environment:
            - PORT
            - MYSQL_HOST
            - MYSQL_PORT
            - MYSQL_USERNAME
            - MYSQL_DATABASE
            - MYSQL_PASSWORD
            - JWT_SECRET
            - JWT_REFRESH
            - REDIS_HOST
        networks:
            - hotel_booking_hotel-net

    redis:
        image: redis:6.0.16-alpine
        container_name: hotel_redis
        command: redis-server --appendonly yes --bind 0.0.0.0
        ports:
            - "6379:6379"
        networks:
            - hotel_booking_hotel-net
        volumes:
            - redis_data:/data

    redis-cli:
        image: redis:6.0.16-alpine
        container_name: redis_cli
        depends_on:
            - redis
        command: redis-cli -h redis
        stdin_open: true
        tty: true
        networks:
            - hotel_booking_hotel-net

volumes:
    redis_data:

networks:
    hotel_booking_hotel-net:
        driver: bridge
